### ISSUE TITLE
点击第二个tab，调用tabBarOnPress，navigation.state.params 没有传对应的参数问题。

### ISSUE THREAD

**Issue by kaixiniOS** [RabbitDream/ReactNavigationDemo#7]
![qq20180607-141233](https://user-images.githubusercontent.com/39097014/41081300-e6db1bbc-6a5c-11e8-9fa0-b4734010a9bd.png)

**Comment by CodeXYu** [comment]
新版本应该是有改动，欢迎查看我的文章更新
